##### RPC and REST configs #####

# RPC endpoint for ethereum chain
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/ejZFfc7ZMLAJHNRnIHbPRH9EmVSCJyVM"
#eth_rpc_url = "http://localhost:9545"

# RPC endpoint for bor chain
#bor_rpc_url = "http://localhost:8545"
#bor_rpc_url = "https://polygon.llamarpc.com/rpc/01GZXEPPVX8JVKVFQK3A7YD8J1"
bor_rpc_url = "https://chemikle"

# RPC endpoint for tendermint
tendermint_rpc_url = "http://0.0.0.0:26657"
